name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy Static HTML App
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 4006e7851624203ed4c5930c3033d3acc22f94092d849791468ff66cfd74062006-afa22f9d-a338-4e89-aff3-2c0509e310020030108082d7fc03
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"              # Hvor dine HTML-filer ligger
          output_location: "."           # Brug roden som output
          app_build_command: ""          # Undgå build helt
